language: python
python:
  - "3.4"
cache: pip
install:
  - pip install freeze
  - pip freeze > requirements.txt
  - ls -al
  - cat requirements.txt
  - pip install -r requirements.txt
script:
  - pytest -q test_wallet.py
